server:
  port: 8081

spring:
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/sky_take_out?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: "123456"
  redis:
    host: localhost
    post: 6379
    database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    admin-secret-key: itcast
    admin-ttl: 720000000
    admin-token-name: token
    user-secret-key: itcast
    user-ttl: 720000000
    user-token-name: authentication
  aws-s3:
    region: us-east-1
    bucket-name: sky-take-out-files

  wechat:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_SECRET}


